### ISSUE TITLE
Valid event names trigger - Error: No spaces allowed in events list 

### ISSUE THREAD

**Issue by emmanuelbuah** [PostHog/event-sequence-timer-plugin#2]
### Background
This plug expects the string format "(eventA,eventB),(eventC,eventD)" with no white spaces but there isn't a hard rule that says events name cannot have white spaces. PostHog's own sdk produce events with spaces in their names eg. Application Opened & Application Backgrounded from the reactive native sdk.  

### Issue
Thus the format "(Application Opened,Application Backgrounded)" should be a valid format but throws Error: No spaces allowed in events list.

This culprit is 
https://github.com/PostHog/event-sequence-timer-plugin/blob/5fb1e844bddda680059130a1d24a99216c1cc682/index.js#L2

**Comment by pjhul** [comment]
Hey @emmanuelbuah! Thanks for creating this issue and apologies on the delayed response. Totally agree that this is a game breaker for most people; I'm going to go through and open a PR to fix this that should get merged early next week 👍
